#ifndef __UIMainFrame__
#define __UIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "UI.h"

/** Implementing MainFrame */
class UIMainFrame : public MainFrame
{
public:
	/** Constructor */
	UIMainFrame( wxWindow* parent );
};

#endif // __UIMainFrame__
