#ifndef __UIMainFrame__
#define __UIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "UI.h"

#include <DB/AppDB.h>

/** Implementing MainFrame */
class UIMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.
	void onMyButton( wxCommandEvent& event );
	
public:
	/** Constructor */
	UIMainFrame( wxWindow* parent );
        
        private:
            AppDB* m_db;
};

#endif // __UIMainFrame__
